name: Combine PRs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    if: github.repository == 'poolifier/poolifier-deno'
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v5.0.0
