name: Internal benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  deployments: write

jobs:
  internal-benchmark:
    if: github.repository == 'poolifier/poolifier-deno'
    # runs-on: [self-hosted, internal-benchmark]
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run production benchmark
        run: deno task benchmark | tee ./benchmarks/internal/output.txt
#       - name: Store production benchmark result
#         uses: benchmark-action/github-action-benchmark@v1
#         with:
#           name: Internal benchmark
#           tool: 'benchmarkjs'
#           output-file-path: ./benchmarks/internal/output.txt
#           github-token: ${{ secrets.BENCHMARK_RESULTS_TOKEN }}
#           auto-push: true
#           alert-threshold: '200%'
#           comment-on-alert: true
#           fail-on-alert: true
#           max-items-in-chart: 100
#           gh-repository: 'github.com/poolifier/benchmark-results'
